// Copyright 2015 The Project Buendia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License.  You may obtain a copy
// of the License at: http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distrib-
// uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
// OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
// specific language governing permissions and limitations under the License.

package org.projectbuendia.client.models;

import android.content.ContentResolver;

import org.projectbuendia.client.resolvables.ResStatus;
import java.util.HashMap;
import java.util.HashSet;

/**
 * Defines hardcoded concept ids expected to exist on the OpenMRS server. Over time, values in this
 * file should be phased out and replaced with modular configuration, either on the server or the
 * client.
 */
public class ConceptUuids {
    public static final String GENERAL_CONDITION_UUID = "a3657203-cfed-44b8-8e3f-960f8d4cf3b3";
    public static final String IV_UUID = "f50c9c63-3ff9-4c26-9d18-12bfc58a3d07";
    public static final String PREGNANCY_UUID = "5272AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    // Persistent fields
    public static final HashSet<String> PERSISTENT_FIELDS = new HashSet<>();

    static {
        // TODO: Determine from the profile which fields should be persistent (on a per form basis), instead of here

        // These are case insensitive

        // Most of the time if you have a multi_select field used in a tile
        // you will want to list it as a persistent field; otherwise when you submit any
        // form containing that field and leave it blank, it will set it back to null.

        // Diagnoses
        PERSISTENT_FIELDS.add("5272AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("f50c9c63-3ff9-4c26-9d18-12bfc58a3d07");
        PERSISTENT_FIELDS.add("1777000619AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000620AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777138868AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777000124AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777139457AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777145443AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777122604AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777148353AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777119356AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777000199AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777113224AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777149609AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000622AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777114431AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777149579AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777149716AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000700AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000701AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777114100AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777113809AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777121392AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777121009AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777114190AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("121375AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777159950AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777160155AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000645AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000646AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000647AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777005334AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777139438AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777120755AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777139407AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777139437AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000626AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777115247AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777143597AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777147267AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000627AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777136292AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777119905AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777112287AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000702AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777137693AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777150555AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777000134AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777124654AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777124650AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777000140AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777118731AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777148705AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777126707AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000628AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000629AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777146166AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000630AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000631AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000632AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777152209AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777115886AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777111633AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777127990AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777000892AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("124957AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777127394AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000633AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777114675AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777114702AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777123084AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777117152AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000635AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777115753AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777156204AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777111873AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777161355AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777111904AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000636AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777111946AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777124033AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777111967AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777117825AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777124028AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777138571AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        // Complications
        PERSISTENT_FIELDS.add("777138061AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777117326AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("113054AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777118876AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("122983AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777147241AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777138099AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("150915AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000637AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777130473AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000638AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000639AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000640AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("777135595AAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000641AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000642AAAAAAAAAAAAAAAAAAAAAAAAAA");
        // Admission tiles
        PERSISTENT_FIELDS.add("1777000589AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000590AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000591AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000592AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000593AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000594AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000595AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1777000601AAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1659AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1396AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        PERSISTENT_FIELDS.add("1401AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

    }

    public static final String PULSE_UUID = "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String PCR_NP_UUID = "162826AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String PCR_L_UUID = "162827AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String FIRST_SYMPTOM_DATE_UUID = "1730AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String ADMISSION_DATE_UUID = "162622AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String GENERAL_CONDITION_WELL_UUID = "1855AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String GENERAL_CONDITION_UNWELL_UUID =
        "137793AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String GENERAL_CONDITION_CRITICAL_UUID =
        "2827e7ac-10c1-4d3f-9fa4-0239771d8548";
    public static final String GENERAL_CONDITION_PALLIATIVE_UUID =
        "7cea1f8f-88cb-4f9c-a9d6-dc28d6eaa520";
    public static final String GENERAL_CONDITION_CONVALESCENT_UUID =
        "119844AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String GENERAL_CONDITION_DISCHARGED_NON_CASE =
        "e4a20c4a-6f13-11e4-b315-040ccecfdba4";
    public static final String GENERAL_CONDITION_CURED =
        "159791AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    public static final String GENERAL_CONDITION_SUSPECTED_DEAD =
        "91dc5fcc-fa9e-4ccd-8cd0-0d203923493f";
    public static final String GENERAL_CONDITION_CONFIRMED_DEAD =
        "160432AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String[] GENERAL_CONDITION_UUIDS = new String[] {
        GENERAL_CONDITION_WELL_UUID,
        GENERAL_CONDITION_UNWELL_UUID,
        GENERAL_CONDITION_CRITICAL_UUID,
        GENERAL_CONDITION_PALLIATIVE_UUID,
        GENERAL_CONDITION_CONVALESCENT_UUID,
        GENERAL_CONDITION_SUSPECTED_DEAD,
        GENERAL_CONDITION_CONFIRMED_DEAD,
        GENERAL_CONDITION_CURED,
        GENERAL_CONDITION_DISCHARGED_NON_CASE
    };

    /** UUID for the (question) concept for the temperature. */
    public static final String TEMPERATURE_UUID = "5088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (question) concept for the notes field. */
    public static final String NOTES_UUID = "162169AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept None. */
    public static final String NONE_UUID = "1107AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept Mild. */
    public static final String MILD_UUID = "1148AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept Moderate. */
    public static final String MODERATE_UUID = "1499AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept Severe. */
    public static final String SEVERE_UUID = "1500AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept of Yes. */
    public static final String YES_UUID = "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept of No. */
    public static final String NO_UUID = "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for the (answer) concept of the answer is unknown. */
    public static final String UNKNOWN_UUID = "1067AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for indicating a patient can eat solid food. */
    public static final String SOLID_FOOD_UUID = "159597AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** UUID for Normal. */
    public static final String NORMAL_UUID = "1115AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    /** Returns the {@link ResStatus} for the specified condition UUID. */
    public static ResStatus getResStatus(String conditionUuid) {
        if (conditionUuid == null) {
            return ResStatus.UNKNOWN;
        }

        switch (conditionUuid) {
            case ConceptUuids.GENERAL_CONDITION_WELL_UUID:
                return ResStatus.WELL;
            case ConceptUuids.GENERAL_CONDITION_UNWELL_UUID:
                return ResStatus.UNWELL;
            case ConceptUuids.GENERAL_CONDITION_CRITICAL_UUID:
                return ResStatus.CRITICAL;
            case ConceptUuids.GENERAL_CONDITION_PALLIATIVE_UUID:
                return ResStatus.PALLIATIVE;
            case ConceptUuids.GENERAL_CONDITION_CONVALESCENT_UUID:
                return ResStatus.CONVALESCENT;
            case ConceptUuids.GENERAL_CONDITION_DISCHARGED_NON_CASE:
                return ResStatus.DISCHARGED_NON_CASE;
            case ConceptUuids.GENERAL_CONDITION_CURED:
                return ResStatus.DISCHARGED_CURED;
            case ConceptUuids.GENERAL_CONDITION_SUSPECTED_DEAD:
                return ResStatus.SUSPECTED_DEAD;
            case ConceptUuids.GENERAL_CONDITION_CONFIRMED_DEAD:
                return ResStatus.CONFIRMED_DEAD;
            default:
                return ResStatus.UNKNOWN;
        }
    }

    private ConceptUuids() {
    }
}
